<?php

/**
 * Implements hook_editor_js_settings_alter().
 */
function office2013_skin_editor_js_settings_alter(array &$settings) {
  foreach (array_keys($settings['editor']['formats']) as $text_format_id) {
    if ($settings['editor']['formats'][$text_format_id]['editor'] === 'ckeditor') {
      $settings['editor']['formats'][$text_format_id]['editorSettings']['skin'] = 'office2013,' . base_path() . drupal_get_path('module', 'office2013_skin') . '/skin/office2013/';
    }
  }
}